server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///heyu?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.1.156
  rabbitmq:
    host: 192.168.1.156
    virtual-host: /heyu
    username: heyu
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

mybatis:
  type-aliases-package: com.heyu.user.pojo