server:
  port: 10010
spring:
  application:
    name: heyu-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/**  # 搜索微服务
    user-service: /user/**  # 用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
    order-service: /order/** # 订单微服务
  add-host-header: true # 携带请求本身的head头信息
  sensitive-headers: # 配置禁止使用的头信息，设置为null否则set-cookie无效
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
heyu:
  jwt:
    pubKeyPath: E:\\GraduationProject\\172021139\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: HY_TOKEN
  filter:
    allowPaths: #白名单路径
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/home
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000