server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.80.128
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10 # 10秒拉取一次微服务
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
heyu:
  jwt:
    pubKeyPath: E:\\GraduationProject\\172021139\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: HY_TOKEN