server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.80.128
    username: heyu
    password: root
    virtual-host: /heyu
heyu:
  sms:
    accessKeyId:  # AccessKeyId
    accessKeySecret: # AccessKeySecret
    signName:  # 签名名称
    verifyCodeTemplate:  # 模板名称
