server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.80.128:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.80.128
    username: heyu
    password: root
    virtual-host: /heyu
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10 # 10秒拉取一次微服务
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期